/** KPCG Climate Intelligence production contracts. */
export type GeographyType='country'|'county'|'subcounty'|'ward'|'facility'|'point'|'gridcell';
export type ObservationValueType='observed'|'estimated'|'modelled'|'projected'|'provisional';
export type ObservationStatus='verified'|'provisional'|'stale'|'superseded'|'unavailable';
export interface Geography{id:string;type:GeographyType;code:string;name:string;parentId:string|null;geometry?:unknown;centroid?:[number,number];population?:number|null;metadata:Record<string,unknown>}
export interface IndicatorThreshold{id:string;label:string;min?:number|null;max?:number|null;category?:string|null;visualToken:string;nonColourEncoding?:'solid'|'dashed'|'hatched'|'dotted'}
export interface Indicator{id:string;code:string;name:string;shortName:string;description:string;domain:string;subdomain:string;framework:string[];frameworkIndicatorCode?:string|null;definition:string;numerator?:string|null;denominator?:string|null;unit?:string|null;methodology:string;direction:'higher-worse'|'higher-better'|'context-dependent'|'neutral';aggregationMethod:string;geographicResolution:GeographyType[];temporalResolution:string;updateFrequency:string;sourceOrganisation:string;sourceDataset?:string|null;sourceUrl?:string|null;licence?:string|null;benchmark?:string|number|null;thresholds:IndicatorThreshold[];metadata:Record<string,unknown>;active:boolean}
export interface Observation{id:string;indicatorId:string;geographyId:string;periodStart:string;periodEnd:string;value:number|string|null;unit:string;valueType:ObservationValueType;status:ObservationStatus;confidence?:number|string|null;sourceOrganisation:string;sourceDataset:string;sourceUrl?:string|null;collectedAt?:string|null;publishedAt?:string|null;importedAt:string;lastVerifiedAt?:string|null;notes?:string|null}
export interface PolicyMapping{indicatorId:string;frameworkId:string;targetOrCommitmentId?:string|null;responsibleInstitution?:string|null;evidenceIds:string[];implementationStatus?:string|null;implementationStatusSource?:string|null}
export function publicValue(observation:Observation|null|undefined):number|string|'No data'{if(!observation||observation.value===null||observation.value===undefined)return'No data';return observation.value}
export function canCalculatePercentageChange(previous:Observation,current:Observation):boolean{return typeof previous.value==='number'&&typeof current.value==='number'&&previous.value!==0}
